### PR TITLE
Upgrade quartz dependency

### PR DESCRIPTION
**Pull request by kalaiyarasiganeshalingam**
## Purpose
$Subject

Fixes: https://github.com/wso2-enterprise/internal-support-ballerina/issues/437

## Checklist
- [ ] Linked to an issue
- [ ] Updated the changelog
- [ ] Added tests
- [ ] Updated the spec
- [ ] Checked native-image compatibility

### CODE REVIEW

**Comment by dilanSachi** [comment]
Can we use rc1 dependencies in our libs?

**Comment by kalaiyarasiganeshalingam** [comment]
> Can we use rc1 dependencies in our libs?

We are using 2.3.2. Quartz's next big lib hasn't been released. Updated versions are in RC, and the issue suggests the version in RC as well.
https://mvnrepository.com/artifact/org.quartz-scheduler/quartz

@daneshk @keizer619 Please give your suggestion.

**Comment by daneshk** [comment]
> > Can we use rc1 dependencies in our libs?
> 
> We are using 2.3.2. Quartz's next major version lib hasn't been released yet. Updated versions are in RC, and the issue suggests the version in RC as well. https://mvnrepository.com/artifact/org.quartz-scheduler/quartz
> 
> @daneshk @keizer619 Please give your suggestion.

According to the quartz issue thread[1], this vulnerability does impact only if we expose the connection factory to be configured by the user. otherwise, there is no way to be vulnerable to the issue. They are still discussing whether it should handled at the application level. IMO, we are not impacted by this. and we can't go with rc1 release.

1. https://github.com/quartz-scheduler/quartz/issues/943

**Comment by dilanSachi** [comment]
> According to the quartz issue thread[1], this vulnerability does impact only if we expose the connection factory to be configured by the user. otherwise, there is no way to be vulnerable to the issue. They are still discussing whether it should handled at the application level. IMO, we are not impacted by this. and we can't go with rc1 release.
> 
> 1. [There's a code injection vulnerability of `org.quartz.jobs.ee.jms.SendQueueMessageJob.execute` quartz-scheduler/quartz#943](https://github.com/quartz-scheduler/quartz/issues/943)

If we are not impacted, i guess we can ignore the vulnerability since we cannot use rc1 builds as well

**Pull request closed without merging**
